import type { TeamWaveSchedule } from '../domain/race-event.js';

export interface PdfBranding {
  teamDisplayName: string;
  primaryColor: string;
  tertiaryColor: string;
  logoUrl: string | null;
}

const DEFAULT_BRANDING: PdfBranding = {
  teamDisplayName: '',
  primaryColor: '#333333',
  tertiaryColor: '#F5F5F5',
  logoUrl: null,
};

export class PdfExportService {
  async generatePdf(
    schedule: TeamWaveSchedule,
    branding?: Partial<PdfBranding>,
    eventLocation?: string,
  ): Promise<Buffer> {
    // Lazy-import pdfkit to avoid loading native modules at Lambda cold start
    const PDFDocument = (await import('pdfkit')).default;
    const brand = { ...DEFAULT_BRANDING, ...branding };

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 40, bottom: 40, left: 40, right: 40 },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.renderHeader(doc, schedule, brand, eventLocation);
      this.renderSummary(doc, schedule, brand);
      this.renderSchedule(doc, schedule, brand);

      doc.end();
    });
  }

  generateFilename(teamName: string, eventDate: string): string {
    const sanitized = teamName.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_');
    return `${sanitized}_${eventDate}_schedule.pdf`;
  }

  private renderHeader(
    doc: PDFKit.PDFDocument,
    schedule: TeamWaveSchedule,
    brand: PdfBranding,
    eventLocation?: string,
  ): void {
    // Header background
    doc.rect(0, 0, doc.page.width, 80).fill(brand.primaryColor);

    // Team name
    const displayName = brand.teamDisplayName || schedule.teamName;
    doc.fillColor('#FFFFFF').fontSize(20).font('Helvetica-Bold');
    doc.text(displayName, 50, 15, { width: doc.page.width - 100 });

    // Event info
    doc.fontSize(10).font('Helvetica');
    doc.text(
      `${schedule.eventName}  •  ${schedule.eventDate}${eventLocation ? `  •  ${eventLocation}` : ''}`,
      50,
      45,
      { width: doc.page.width - 100 },
    );

    doc.moveDown(2);
    doc.y = 100;
  }

  private renderSummary(
    doc: PDFKit.PDFDocument,
    schedule: TeamWaveSchedule,
    brand: PdfBranding,
  ): void {
    const leftMargin = 40;
    const pageWidth = doc.page.width - leftMargin * 2;

    // Section title
    doc.fillColor('#333333').fontSize(10).font('Helvetica-Bold');
    doc.text('Wave Summary', leftMargin, doc.y, { lineBreak: false });
    doc.y += 16;

    // Table header
    const sumCols = [160, 70, 70, 70, 80];
    const sumHeaders = ['Wave', 'Stage', 'Race Start', 'Athletes', 'Categories'];
    const sumWidth = sumCols.reduce((s, w) => s + w, 0);

    const thY = doc.y;
    doc.rect(leftMargin, thY, sumWidth, 16).fill(brand.primaryColor);
    doc.fillColor('#FFFFFF').fontSize(7).font('Helvetica-Bold');
    let x = leftMargin;
    for (let i = 0; i < sumHeaders.length; i++) {
      doc.text(sumHeaders[i], x + 4, thY + 4, { width: sumCols[i] - 8, lineBreak: false });
      x += sumCols[i];
    }
    doc.y = thY + 16;

    // One row per wave
    doc.font('Helvetica').fontSize(8);
    let rowIndex = 0;
    for (const wave of schedule.waves) {
      const firstCat = wave.categories[0];
      const athleteCount = wave.categories.reduce((s, c) => s + c.athletes.length, 0);
      const categoryNames = wave.categories.map((c) => c.categoryName).join(', ');
      const rowY = doc.y;

      if (rowIndex % 2 === 1) {
        doc.rect(leftMargin, rowY, sumWidth, 14).fill(brand.tertiaryColor);
      }

      doc.fillColor('#000000');
      const rowValues = [
        wave.waveName,
        firstCat?.stageTime ?? '—',
        firstCat?.startTime ?? '—',
        String(athleteCount),
        categoryNames,
      ];
      x = leftMargin;
      for (let i = 0; i < rowValues.length; i++) {
        doc.text(rowValues[i], x + 4, rowY + 3, { width: sumCols[i] - 8, lineBreak: false });
        x += sumCols[i];
      }
      doc.y = rowY + 14;
      rowIndex++;
    }

    // Thin rule below summary
    doc.y += 6;
    doc.rect(leftMargin, doc.y, pageWidth, 0.5).fill('#CCCCCC');
    doc.y += 10;

    // Footer line for summary page
    const footerY = doc.page.height - 40;
    doc.fontSize(7).fillColor('#999999').font('Helvetica');
    doc.text(
      `Generated by Switchback  •  ${schedule.totalAthletes} athletes  •  ${schedule.waves.length} waves`,
      leftMargin,
      footerY,
      { lineBreak: false },
    );
  }

  private renderSchedule(
    doc: PDFKit.PDFDocument,
    schedule: TeamWaveSchedule,
    brand: PdfBranding,
  ): void {
    const leftMargin = 40;
    const colWidths = [120, 40, 65, 50, 50, 50, 50];
    const headers = ['Athlete', 'Bib', 'Wave Meeting', 'WU Start', 'WU End', 'Stage', 'Race'];
    const tableWidth = colWidths.reduce((s, w) => s + w, 0);

    for (const wave of schedule.waves) {
      // Each wave gets its own page
      doc.addPage();
      doc.y = 40;

      // Wave header
      const waveY = doc.y;
      doc.rect(leftMargin, waveY, tableWidth, 22).fill(brand.primaryColor);
      doc.fillColor('#FFFFFF').fontSize(11).font('Helvetica-Bold');
      doc.text(wave.waveName, leftMargin + 6, waveY + 5, { width: tableWidth - 12, lineBreak: false });
      doc.y = waveY + 26;

      for (const cat of wave.categories) {
        // Category sub-header
        const catY = doc.y;
        doc.rect(leftMargin, catY, tableWidth, 18).fill(brand.tertiaryColor);
        doc.fillColor('#333333').fontSize(9).font('Helvetica-Bold');
        const catLabel = `${cat.categoryName}  (Start: ${cat.startTime}, Stage: ${cat.stageTime}, ${cat.laps ?? '—'} laps)`;
        doc.text(catLabel, leftMargin + 6, catY + 4, { width: tableWidth - 12, lineBreak: false });
        doc.y = catY + 20;

        // Column headers — fix y for all columns before the loop
        doc.fillColor('#666666').fontSize(7).font('Helvetica-Bold');
        const headerY = doc.y;
        let x = leftMargin;
        for (let i = 0; i < headers.length; i++) {
          doc.text(headers[i], x + 3, headerY + 2, { width: colWidths[i] - 6, lineBreak: false });
          x += colWidths[i];
        }
        doc.y = headerY + 14;

        // Athlete rows
        doc.font('Helvetica').fontSize(8).fillColor('#000000');
        let rowIndex = 0;
        for (const athlete of cat.athletes) {
          if (doc.y > doc.page.height - 50) {
            doc.addPage();
            doc.y = 40;
          }

          const rowY = doc.y;

          // Alternating row background
          if (rowIndex % 2 === 1) {
            doc.rect(leftMargin, rowY, tableWidth, 14).fill('#F9F9F9');
            doc.fillColor('#000000');
          }

          x = leftMargin;
          const values = [
            `${athlete.lastName}, ${athlete.firstName}`,
            athlete.bibNumber,
            athlete.logistics?.waveMeetingTime ?? '',
            athlete.logistics?.warmupStart ?? '',
            athlete.logistics?.warmupEnd ?? '',
            athlete.logistics?.stagingTime ?? '',
            athlete.logistics?.raceStart ?? '',
          ];

          for (let i = 0; i < values.length; i++) {
            doc.text(values[i], x + 3, rowY + 3, { width: colWidths[i] - 6, lineBreak: false });
            x += colWidths[i];
          }

          doc.y = rowY + 14;
          rowIndex++;
        }

        doc.y += 4;
      }

      doc.y += 8;
    }
  }
}
